//
//  Copyright (c) 2015 IBM Corp. All rights reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
//  except in compliance with the License. You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software distributed under the
//  License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
//  either express or implied. See the License for the specific language governing permissions 
//  and limitations under the License.
using System;

namespace IBM.Cloudant.Client
{
    /// <summary>
    /// Exception type used by the Cloudant Client to report exceptions
    /// while working with data services.
    /// </summary>
    /// <remarks>
    /// This class contains exceptions generated by the data services classes.
    /// </remarks>
    public class DataException: Exception
    {
        /// <summary>
        /// Exception code: The Cloudant account is invalid.
        /// </summary>
        public static readonly int Configuration_InvalidAccountSettings = 010;

        /// <summary>
        /// Exception code: The interceptor(s) provided were not valid.
        /// </summary>
        public static readonly int Configuration_InvalidHttpInterceptor = 011;

        /// <summary>
        /// Exception code: Error happened while querying a database.
        /// </summary>
        public static readonly int Database_QueryError = 002;

        /// <summary>
        /// Exception code: Error happened while creating or modifing a database.
        /// </summary>
        public static readonly int Database_DatabaseModificationFailure = 100;

        /// <summary>
        /// Exception code: Error happened while creating a document.
        /// </summary>
        public static readonly int Database_CreateDocumentRevisionFailure = 102;

        /// <summary>
        /// Exception code: Error happened while fetching a document.
        /// </summary>
        public static readonly int Database_ReadDocumentRevisionFailure = 103;

        /// <summary>
        /// Exception code: Error happened while deleting a document.
        /// </summary>
        public static readonly int Database_DeleteDocumentRevisionFailure = 104;

        /// <summary>
        /// Exception code: Error happened while creating or modifying an index.
        /// </summary>
        public static readonly int Database_IndexModificationFailure = 105;


        private string domain { get; }

        /// <summary>
        /// Gets the error code for this exception.
        /// </summary>
        /// <value>The error code.</value>
        public int code { get; }

        /// <summary>
        /// Initializes a new instance of the <see cref="IBM.Cloudant.Client.DataException"/> class.
        /// </summary>
        /// <param name="code">Code for the exception.  Must be one of the static values defined in <see cref="IBM.Cloudant.Client.DataException"/></param>
        /// <param name="message">Message.</param>
        public DataException(int code, String message)
            : base(message)
        {
            this.code = code;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="IBM.Cloudant.Client.DataException"/> class.
        /// </summary>
        /// <param name="code">Code for the exception.  Must be one of the static values defined in <see cref="IBM.Cloudant.Client.DataException"/></param>
        /// <param name="message">Message.</param>
        /// <param name="cause">Cause.</param>
        public DataException(int code, String message, Exception cause)
            : base(message, cause)
        {
            this.code = code;
        }

    }
}

